/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as Cca2Import } from './app/$cca2'
import { Route as IndexImport } from './app/index'

// Create/Update Routes

const Cca2Route = Cca2Import.update({
  id: '/$cca2',
  path: '/$cca2',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$cca2': {
      id: '/$cca2'
      path: '/$cca2'
      fullPath: '/$cca2'
      preLoaderRoute: typeof Cca2Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$cca2': typeof Cca2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$cca2': typeof Cca2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$cca2': typeof Cca2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$cca2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$cca2'
  id: '__root__' | '/' | '/$cca2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Cca2Route: typeof Cca2Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Cca2Route: Cca2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$cca2"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$cca2": {
      "filePath": "$cca2.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
